name: "CI: Linting"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.64

permissions:
  contents: read
  pull-requests: read
  checks: write


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
